### ISSUE TITLE
[Request] Add the ability to adjust the vertical offset of the player

### ISSUE THREAD

**Issue by BowlPlatt** [UsrLightmann/Vinyl#2]
As the title suggests, the ability to move the player up/down would be useful. The player obscures part of my Speculum setup, particularly the weather label. See:
![15DDDABC-8648-4B83-9D42-AAF7B4665CCF](https://user-images.githubusercontent.com/51038463/109990827-c16ea980-7cd7-11eb-9277-7c01b1a82aba.png)

I appreciate that you do this for free and it is a great tweak, but I don’t have the knowledge to contribute, so I hope you add this as a functionality whenever you can, in your own time.
Thanks!

**Comment by L1ghtmann** [comment]
Hey! This can be achieved with Lower by S1ris.
