### ISSUE TITLE
“Thinner” buttons

### ISSUE THREAD

**Issue by rml9ty** [UsrLightmann/Vinyl#3]
I would love an option to make the buttons (back, Pause/Play, skip) less pronounced. Like a non bold version. 

I also feel like they are very slightly too high for it to look symmetrical.

Keep up the good work!

**Comment by dinouse** [comment]
yeah same but for me. I would love if the play button forward and backward just gone. I hope you can make it. Love your tweaks!!

**Comment by L1ghtmann** [comment]
The buttons are stock, so the only thing I could do is shrink their footprint (which would not change how they look aesthetically). 

And their position being slightly off is intentional, as the progress slider needs adequate input space.
