### ISSUE TITLE
Suggestion: Audio Source Icon Toggle

### ISSUE THREAD

**Issue by irobles24** [UsrLightmann/Vinyl#4]
![IMG_2043](https://user-images.githubusercontent.com/80562544/114285202-f2e73d00-9a1a-11eb-8571-f01ca46afaa9.jpg)
I would love a toggle that could remove the music player symbol at the bottom right corner of the artwork. (In this example it is Spotify, but it shows for all.)

**Comment by L1ghtmann** [comment]
Will be adding this in the next update.

**Comment by L1ghtmann** [comment]
Added in v1.1.0.
